"""
export_weights.py
-----------------
Exports the trained float32 model weights as C header files.
These headers are #included directly by the C inference engine —
no file I/O required at inference time.

Each layer's weights are quantized to int8 (Q7 format) and written
as static const int8_t arrays with accompanying scale factors.

Output (in engine/include/weights/):
  conv1_weights.h
  conv2_weights.h
  conv3_weights.h
  fc1_weights.h
  fc2_weights.h
  model_params.h   — architecture constants (layer sizes, scales)
"""

import os
import sys
import numpy as np
import torch

sys.path.insert(0, os.path.dirname(__file__))
from train import SensorCNN

CHECKPOINT_DIR  = os.path.join(os.path.dirname(__file__), "checkpoints")
WEIGHTS_OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "engine", "include", "weights")


# ── Quantization Helpers ───────────────────────────────────────────────────────

def quantize_to_int8(weights: np.ndarray) -> tuple[np.ndarray, float]:
    """
    Symmetric per-tensor quantization to int8 (Q7 format).
    scale = max_abs / 127.0
    quantized = clip(round(weights / scale), -128, 127)

    Returns:
        quantized : int8 numpy array
        scale     : float32 scale factor (needed for dequantization in C)
    """
    max_abs = np.max(np.abs(weights))
    if max_abs < 1e-8:
        return np.zeros_like(weights, dtype=np.int8), 1.0

    scale     = max_abs / 127.0
    quantized = np.clip(np.round(weights / scale), -128, 127).astype(np.int8)
    return quantized, float(scale)


# ── C Array Writers ────────────────────────────────────────────────────────────

def _format_int8_array(name: str, data: np.ndarray) -> str:
    """Format a numpy int8 array as a C static const int8_t array."""
    flat   = data.flatten()
    values = ", ".join(str(int(v)) for v in flat)
    # Wrap at 12 values per line for readability
    lines  = []
    chunk  = 12
    for i in range(0, len(flat), chunk):
        lines.append("    " + ", ".join(str(int(v)) for v in flat[i:i+chunk]))
    body = ",\n".join(lines)
    return (
        f"static const int8_t {name}[{len(flat)}] = {{\n"
        f"{body}\n"
        f"}};\n"
    )


def _format_float(name: str, value: float) -> str:
    return f"static const float {name} = {value:.10f}f;\n"


def _format_int(name: str, value: int) -> str:
    return f"#define {name} {value}\n"


def _header_guard(name: str) -> tuple[str, str]:
    guard = name.upper().replace(".", "_").replace("/", "_")
    return f"#ifndef {guard}\n#define {guard}\n\n", f"\n#endif // {guard}\n"


def write_header(filename: str, content: str) -> None:
    os.makedirs(WEIGHTS_OUT_DIR, exist_ok=True)
    path = os.path.join(WEIGHTS_OUT_DIR, filename)
    guard_open, guard_close = _header_guard(filename)
    with open(path, "w") as f:
        f.write(f"// Auto-generated by export_weights.py — DO NOT EDIT\n")
        f.write(f"// ENIE Embedded Neural Inference Engine\n\n")
        f.write(guard_open)
        f.write(content)
        f.write(guard_close)
    print(f"  Written: {path}")


# ── Layer Exporters ────────────────────────────────────────────────────────────

def export_conv_layer(layer: torch.nn.Conv1d, idx: int) -> dict:
    """Export a Conv1d layer's weights to a C header."""
    W = layer.weight.detach().numpy()   # shape: (out_ch, in_ch, kernel)
    q, scale = quantize_to_int8(W)

    out_ch, in_ch, kernel = W.shape
    content = (
        f"// Conv{idx} weights: [{out_ch}, {in_ch}, {kernel}]\n"
        f"// Layout: [out_channel][in_channel][kernel_pos]\n\n"
        + _format_int8_array(f"conv{idx}_weights", q)
        + "\n"
        + _format_float(f"conv{idx}_scale", scale)
    )
    write_header(f"conv{idx}_weights.h", content)
    return {"scale": scale, "out_ch": out_ch, "in_ch": in_ch, "kernel": kernel}


def export_fc_layer(layer: torch.nn.Linear, idx: int) -> dict:
    """Export a Linear layer's weights and biases to a C header."""
    W = layer.weight.detach().numpy()   # shape: (out, in)
    b = layer.bias.detach().numpy()     # shape: (out,)

    qW, scale_w = quantize_to_int8(W)
    qb, scale_b = quantize_to_int8(b)

    out_f, in_f = W.shape
    content = (
        f"// FC{idx} weights: [{out_f}, {in_f}]\n\n"
        + _format_int8_array(f"fc{idx}_weights", qW)
        + "\n"
        + _format_float(f"fc{idx}_weight_scale", scale_w)
        + "\n"
        + f"// FC{idx} bias: [{out_f}]\n\n"
        + _format_int8_array(f"fc{idx}_bias", qb)
        + "\n"
        + _format_float(f"fc{idx}_bias_scale", scale_b)
    )
    write_header(f"fc{idx}_weights.h", content)
    return {"scale_w": scale_w, "scale_b": scale_b, "out": out_f, "in": in_f}


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    print("=" * 55)
    print("ENIE — Weight Export to C Headers")
    print("=" * 55)

    # Load trained model
    model_path = os.path.join(CHECKPOINT_DIR, "model_float32.pt")
    if not os.path.exists(model_path):
        print(f"Model not found: {model_path}\nRun train.py first.")
        return

    model = torch.load(model_path, map_location="cpu", weights_only=False)
    model.eval()

    print(f"\nExporting weights to: {os.path.abspath(WEIGHTS_OUT_DIR)}")
    print()

    # Extract conv layers (indices 0, 4, 8 in conv_block — after BN fusion skip)
    conv_block = model.conv_block
    conv_layers = [(i, m) for i, m in enumerate(conv_block) if isinstance(m, torch.nn.Conv1d)]
    fc_layers   = [(i, m) for i, m in enumerate(model.classifier) if isinstance(m, torch.nn.Linear)]

    params = {}

    print("Conv layers:")
    for conv_idx, (_, layer) in enumerate(conv_layers, 1):
        info = export_conv_layer(layer, conv_idx)
        params[f"conv{conv_idx}"] = info

    print("\nFC layers:")
    for fc_idx, (_, layer) in enumerate(fc_layers, 1):
        info = export_fc_layer(layer, fc_idx)
        params[f"fc{fc_idx}"] = info

    # Write model_params.h — architecture constants for C engine
    print("\nWriting model_params.h...")
    c1 = params["conv1"]
    c2 = params["conv2"]
    c3 = params["conv3"]
    f1 = params["fc1"]
    f2 = params["fc2"]

    model_params = (
        "// Model architecture constants\n\n"
        + _format_int("SIGNAL_LENGTH",    128)
        + _format_int("CONV1_IN_CH",      c1["in_ch"])
        + _format_int("CONV1_OUT_CH",     c1["out_ch"])
        + _format_int("CONV1_KERNEL",     c1["kernel"])
        + _format_int("CONV2_IN_CH",      c2["in_ch"])
        + _format_int("CONV2_OUT_CH",     c2["out_ch"])
        + _format_int("CONV2_KERNEL",     c2["kernel"])
        + _format_int("CONV3_IN_CH",      c3["in_ch"])
        + _format_int("CONV3_OUT_CH",     c3["out_ch"])
        + _format_int("CONV3_KERNEL",     c3["kernel"])
        + _format_int("POOL_SIZE",        2)
        + _format_int("FC1_IN",           f1["in"])
        + _format_int("FC1_OUT",          f1["out"])
        + _format_int("FC2_IN",           f2["in"])
        + _format_int("FC2_OUT",          f2["out"])
        + _format_int("N_CLASSES",        3)
        + "\n// Weight scale factors\n\n"
        + _format_float("CONV1_SCALE",    c1["scale"])
        + _format_float("CONV2_SCALE",    c2["scale"])
        + _format_float("CONV3_SCALE",    c3["scale"])
        + _format_float("FC1_W_SCALE",    f1["scale_w"])
        + _format_float("FC2_W_SCALE",    f2["scale_w"])
    )
    write_header("model_params.h", model_params)

    print("\n" + "=" * 55)
    print("Export complete! Headers written:")
    for f in sorted(os.listdir(WEIGHTS_OUT_DIR)):
        size = os.path.getsize(os.path.join(WEIGHTS_OUT_DIR, f))
        print(f"  {f:<30s} {size/1024:.1f} KB")
    print("\nNext step: build the C inference engine in engine/")


if __name__ == "__main__":
    main()