// Auto-generated by export_weights.py — DO NOT EDIT
// ENIE Embedded Neural Inference Engine

#ifndef CONV1_WEIGHTS_H
#define CONV1_WEIGHTS_H

// Conv1 weights: [8, 1, 7]
// Layout: [out_channel][in_channel][kernel_pos]

static const int8_t conv1_weights[56] = {
    79, 100, -25, 110, -17, 26, -57, 77, 99, -92, 97, 19,
    80, 11, 56, -23, 90, 14, -59, 32, -52, -30, -58, 67,
    -87, -50, -37, -82, 18, -106, 114, -97, 92, 21, -39, 69,
    6, 87, 3, -46, 35, -35, 50, 108, 71, -43, 62, 23,
    61, -88, -127, -57, -105, 80, 15, 29
};

static const float conv1_scale = 0.0032408452f;

#endif // CONV1_WEIGHTS_H
