// Auto-generated by export_weights.py — DO NOT EDIT
// ENIE Embedded Neural Inference Engine

#ifndef FC2_WEIGHTS_H
#define FC2_WEIGHTS_H

// FC2 weights: [3, 32]

static const int8_t fc2_weights[96] = {
    70, -5, -49, 3, -3, 55, -99, 94, 23, -66, 64, -81,
    -24, 55, 62, -70, -11, -2, 93, 17, -3, 100, -92, -98,
    -50, -38, -103, 114, 115, 104, -84, -50, -90, -24, 107, -13,
    -12, -113, 53, 91, -57, 97, 66, -65, -90, -21, -115, -88,
    66, -56, -66, -61, 72, 66, 96, -127, -89, 42, 77, -32,
    26, -20, 37, 77, 77, -100, -78, 67, 98, -3, 99, -43,
    -77, -27, -109, 26, -114, 103, -85, 85, -100, 6, -88, 63,
    90, -111, -95, 51, 50, 1, 44, -45, 51, -20, -48, 55
};

static const float fc2_weight_scale = 0.0018819534f;

// FC2 bias: [3]

static const int8_t fc2_bias[3] = {
    -127, -68, 53
};

static const float fc2_bias_scale = 0.0012246273f;

#endif // FC2_WEIGHTS_H
