// Auto-generated by export_weights.py — DO NOT EDIT
// ENIE Embedded Neural Inference Engine

#ifndef MODEL_PARAMS_H
#define MODEL_PARAMS_H

// Model architecture constants

#define SIGNAL_LENGTH 128
#define CONV1_IN_CH 1
#define CONV1_OUT_CH 8
#define CONV1_KERNEL 7
#define CONV2_IN_CH 8
#define CONV2_OUT_CH 16
#define CONV2_KERNEL 5
#define CONV3_IN_CH 16
#define CONV3_OUT_CH 16
#define CONV3_KERNEL 3
#define POOL_SIZE 2
#define FC1_IN 256
#define FC1_OUT 32
#define FC2_IN 32
#define FC2_OUT 3
#define N_CLASSES 3

// Weight scale factors

static const float CONV1_SCALE = 0.0032408452f;
static const float CONV2_SCALE = 0.0015937166f;
static const float CONV3_SCALE = 0.0015935800f;
static const float FC1_W_SCALE = 0.0011448346f;
static const float FC2_W_SCALE = 0.0018819534f;

#endif // MODEL_PARAMS_H
